[[constraint]]
  branch = "master"
  name = "github.com/opentracing-contrib/go-stdlib"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.15.0"
